### ISSUE TITLE
Use XDG directory specs on Linux

### ISSUE THREAD

**Issue by LoipesMas** [Flone-dnb/FBugReporter#6]
On Linux it's a standard to use [XDG Base Directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) to decide where files should be stored.
For example, config files would be stored in `$XDG_CONFIG_HOME` and log files in `$XDG_STATE_HOME`. 

This can be easily achieved with [`xdg` crate](https://crates.io/crates/xdg).

**Comment by Flone-dnb** [comment]
Yep. This is also something we should 100% do.
